services:
  frontend:
    image: hanshino/redive_frontend:${FRONTEND_IMAGE_TAG:-latest}
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_frontend-secure.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}_frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}_frontend-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}_frontend-secure.tls.certresolver=leresolver"
      - "traefik.http.routers.${PROJECT_NAME}_frontend-secure.priority=1"
      - "traefik.docker.network=traefik"

  bot:
    image: hanshino/redive_backend:${BACKEND_IMAGE_TAG:-latest}
    env_file: stack.env
    restart: always
    expose:
      - 9527
    networks:
      - infra
      - traefik
    volumes:
      - ${ASSETS_HOST_PATH}:/usr/src/app/assets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_bot-secure.rule=Host(`${APP_DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/webhooks`) || PathPrefix(`/bot-assets`) || PathPrefix(`/socket.io`))"
      - "traefik.http.routers.${PROJECT_NAME}_bot-secure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}_bot-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}_bot-secure.tls.certresolver=leresolver"
      - "traefik.http.routers.${PROJECT_NAME}_bot-secure.priority=100"
      - "traefik.http.services.${PROJECT_NAME}_bot.loadbalancer.server.port=9527"
      - "traefik.docker.network=traefik"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  worker:
    image: hanshino/redive_backend:${BACKEND_IMAGE_TAG:-latest}
    env_file: stack.env
    restart: always
    networks:
      - infra
    volumes:
      - ${ASSETS_HOST_PATH}:/usr/src/app/assets
    command: yarn worker
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

networks:
  traefik:
    external: true
    name: traefik
  infra:
    external: true
    name: infra
