version: "3.5"
services:
  frontend:
    image: hanshino/redive_frontend
    env_file: ./.env
    restart: always
    networks:
      - traefik
      - bot_network
    volumes:
      - ./docker/config:/etc/nginx/conf.d/templates
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_frontend-secure.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}_frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}_frontend-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}_frontend-secure.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik"
    command: /bin/sh -c "envsubst '$$APP_DOMAIN' < /etc/nginx/conf.d/templates/redive.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - bot

  bot:
    image: hanshino/redive_backend
    env_file: ./.env
    restart: always
    expose:
      - 5000
    depends_on:
      - mysql
      - redis
    networks:
      - bot_network
    volumes:
      - ./app/assets:/usr/src/app/assets
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  worker:
    image: hanshino/redive_backend
    env_file: ./.env
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - bot_network
    volumes:
      - ./app/assets:/application/assets
    command: yarn worker
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  mysql:
    env_file: ./.env
    image: mysql
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
      - "mysql_data:/var/lib/mysql"
    restart: always
    expose:
      - "${DB_PORT}"
    networks:
      - bot_network
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_USER": "${DB_USER}"
      "MYSQL_PASSWORD": "${DB_USER_PASSWORD}"
      "MYSQL_ROOT_PASSWORD": "${DB_PASSWORD}"

  redis:
    image: redis:alpine
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    networks:
      - bot_network
    expose:
      - "${REDIS_PORT}"

  crontab:
    build: ./job
    restart: always
    networks:
      - bot_network
    depends_on:
      - mysql
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    env_file: ./.env

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-secure.rule=Host(`${ADMIN_DOMAIN}`)"
      - "traefik.http.routers.admin-secure.entrypoints=websecure"
      - "traefik.http.routers.admin-secure.tls=true"
      - "traefik.http.routers.admin-secure.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik"
    networks:
      - bot_network
      - traefik

  python:
    build: ./opencv
    networks:
      - bot_network
    restart: always
    expose:
      - 3000

networks:
  traefik:
    external: true
    name: traefik
  bot_network:


volumes:
  mysql_data:
