/**
 * 顯示完成出刀列表
 * @param {Context} context
 * @param {Object[]} FinishMemberList
 * @param {String} FinishMemberList[].displayName
 * @param {String} FinishMemberList[].createDTM
 * @param {Boolean} FinishMemberList[].isSignin
 */
exports.showFinishList = (context, FinishMemberList) => {
  let date = new Date();
  const Today = [
    date.getFullYear(),
    ("0" + (date.getMonth() + 1)).substr(-2),
    ("0" + date.getDate()).substr(-2),
  ].join(".");
  let isSignList = FinishMemberList.filter(list => list.isSignin);
  let notSignList = FinishMemberList.filter(list => !list.isSignin);
  context.replyFlex("出刀簽到表", {
    type: "carousel",
    contents: [
      {
        type: "bubble",
        header: {
          type: "box",
          layout: "vertical",
          contents: [
            {
              type: "text",
              text: "🏆成功人士",
              weight: "bold",
              color: "#9B1C31",
            },
          ],
          backgroundColor: "#80C5DE",
        },
        body: {
          type: "box",
          layout: "vertical",
          contents: [
            {
              type: "box",
              layout: "horizontal",
              contents: [
                {
                  type: "text",
                  text: "姓名",
                  weight: "bold",
                  flex: 7,
                },
                {
                  type: "text",
                  text: "時間",
                  weight: "bold",
                  flex: 5,
                },
              ],
            },
            ...isSignList.map(genMemberRow),
          ],
        },
        footer: {
          type: "box",
          layout: "vertical",
          contents: [
            {
              type: "separator",
            },
            {
              type: "box",
              layout: "horizontal",
              contents: [
                {
                  type: "text",
                  text: `總計${isSignList.length}位`,
                  size: "xs",
                  align: "start",
                  flex: 3,
                },
                {
                  type: "text",
                  text: `${Today} Generated by 布丁機器人`,
                  align: "end",
                  color: "#808080",
                  size: "xs",
                  margin: "sm",
                  flex: 9,
                },
              ],
            },
          ],
        },
      },
      {
        type: "bubble",
        header: {
          type: "box",
          layout: "vertical",
          contents: [
            {
              type: "text",
              text: "🎮出刀機器",
              weight: "bold",
              color: "#FEFEFE",
            },
          ],
          backgroundColor: "#9B1C31",
        },
        body: {
          type: "box",
          layout: "vertical",
          contents: [
            {
              type: "box",
              layout: "horizontal",
              contents: [
                {
                  type: "text",
                  text: "姓名",
                  weight: "bold",
                  flex: 7,
                },
                {
                  type: "text",
                  text: "時間",
                  weight: "bold",
                  flex: 5,
                },
              ],
            },
            ...notSignList.map(genMemberRow),
          ],
        },
        footer: {
          type: "box",
          layout: "vertical",
          contents: [
            {
              type: "separator",
            },
            {
              type: "box",
              layout: "horizontal",
              contents: [
                {
                  type: "text",
                  text: `總計${notSignList.length}位`,
                  size: "xs",
                  align: "start",
                  flex: 3,
                },
                {
                  type: "text",
                  text: `${Today} Generated by 布丁機器人`,
                  align: "end",
                  color: "#808080",
                  size: "xs",
                  margin: "sm",
                  flex: 9,
                },
              ],
            },
          ],
        },
      },
    ],
  });
};

function genMemberRow(memberData) {
  let date,
    strDate = "-";
  if (memberData.createDTM) {
    date = new Date(memberData.createDTM);
    strDate =
      [("0" + (date.getMonth() + 1)).substr(-2), date.getDate()].join("/") +
      " " +
      [("0" + date.getHours()).substr(-2), ("0" + date.getMinutes()).substr(-2)].join(":");
  }

  return {
    type: "box",
    layout: "horizontal",
    contents: [
      {
        type: "text",
        text: memberData.displayName || "路人甲",
        flex: 7,
      },
      {
        type: "text",
        text: strDate,
        flex: 5,
      },
    ],
  };
}
