module.exports = [
  {
    name: "Event Dequeue",
    description: "process events from redis queue (user/group tracking, messages, chat exp)",
    period: ["*", "*", "*", "*", "*", "*"],
    immediate: true,
    require_path: "./bin/EventDequeue",
  },
  {
    name: "Chat Exp Update",
    description: "merge chat experience records into database",
    period: ["0", "*/5", "*", "*", "*", "*"],
    immediate: true,
    require_path: "./bin/ChatExpUpdate",
  },
  {
    name: "Trial Expiry Check",
    description: "expire 60-day-old active trials to failed status",
    period: ["0", "5", "0", "*", "*", "*"],
    immediate: false,
    require_path: "./bin/TrialExpiryCheck",
  },
  {
    name: "Broadcast Queue Drainer",
    description:
      "consume BROADCAST_QUEUE_* keys and reply to groups when a fresh token is available",
    period: ["*/30", "*", "*", "*", "*", "*"],
    immediate: false,
    require_path: "./bin/BroadcastQueueDrainer",
  },
  {
    name: "Daily Cleanup",
    description: "clear closed groups, left members, deleted/useless custom commands",
    period: ["0", "0", "0", "*", "*", "*"],
    immediate: false,
    require_path: "./bin/DailyCleanup",
  },
  {
    name: "Chat Exp Events Prune",
    description: "drop chat_exp_events rows older than 30 days (spec line 545)",
    period: ["0", "0", "3", "*", "*", "*"],
    immediate: false,
    require_path: "./bin/ChatExpEventsPrune",
  },
  {
    name: "Daily Ration",
    description: "daily ration for subscribers",
    period: ["10", "*/10", "*", "*", "*", "*"],
    immediate: true,
    require_path: "./bin/DailyRation",
  },
  {
    name: "Clean Expired Subscriber",
    description: "clean expired subscriber",
    period: ["0", "0", "0", "*", "*", "*"],
    immediate: true,
    require_path: "./bin/CleanExpiredSubscriber",
  },
  {
    name: "Weekly Member Audit",
    description: "queue member data for cleanup audit",
    period: ["0", "0", "3", "*", "*", "3"],
    immediate: false,
    require_path: "./bin/WeeklyMemberAudit",
  },
  {
    name: "Consume CleanUp Members",
    description: "process member cleanup queue",
    period: ["0", "*/15", "*", "*", "*", "3"],
    immediate: false,
    require_path: "./bin/ConsumeCleanUpMembers",
  },
  {
    name: "Monthly Reset",
    description: "reset monthly message records",
    period: ["0", "0", "0", "1", "*", "*"],
    immediate: false,
    require_path: "./bin/MonthlyReset",
  },
  {
    name: "Achievement Batch Evaluation",
    description: "batch evaluate milestone achievements for all users",
    period: ["0", "0", "3", "*", "*", "*"],
    immediate: false,
    require_path: "./bin/AchievementCron",
  },
  {
    name: "Title Delivery",
    description: "reassign dynamic titles based on current rankings",
    period: ["0", "10", "3", "*", "*", "*"],
    immediate: false,
    require_path: "./bin/TitleDelivery",
  },
  {
    name: "Daily Quest Process",
    description: "process daily quest rewards",
    period: ["0", "*", "*", "*", "*", "*"],
    immediate: true,
    require_path: "./bin/DailyQuestProcess",
  },
  {
    name: "Race Advance",
    description: "manage race lifecycle: create, advance rounds, settle bets",
    period: ["0", "*", "*", "*", "*", "*"],
    immediate: true,
    require_path: "./bin/RaceAdvance",
  },
  {
    name: "Auto Gacha",
    description: "nightly auto daily-draw for subscribers with auto_daily_gacha opt-in",
    period: require("config").get("autoGacha.schedule"),
    immediate: false,
    require_path: "./bin/AutoGacha",
  },
  {
    name: "Janken Daily Rewards",
    description: "credit daily women-stones to active janken players (kill-switched in config)",
    period: ["0", "10", "0", "*", "*", "*"],
    immediate: false,
    require_path: "./bin/JankenDailyRewards",
  },
];
