module.exports = [
  {
    name: "Event Dequeue",
    description: "process events from redis queue (user/group tracking, messages, chat exp)",
    period: ["*", "*", "*", "*", "*", "*"],
    immediate: true,
    require_path: "./bin/EventDequeue",
  },
  {
    name: "Chat Exp Update",
    description: "merge chat experience records into database",
    period: ["0", "*/5", "*", "*", "*", "*"],
    immediate: true,
    require_path: "./bin/ChatExpUpdate",
  },
  {
    name: "Chat Ranking",
    description: "refresh chat level rankings",
    period: ["12", "*/10", "*", "*", "*", "*"],
    immediate: false,
    require_path: "./bin/ChatRanking",
  },
  {
    name: "Daily Cleanup",
    description: "clear closed groups, left members, deleted/useless custom commands",
    period: ["0", "0", "0", "*", "*", "*"],
    immediate: false,
    require_path: "./bin/DailyCleanup",
  },
  {
    name: "Daily Ration",
    description: "daily ration for subscribers",
    period: ["10", "*/10", "*", "*", "*", "*"],
    immediate: true,
    require_path: "./bin/DailyRation",
  },
  {
    name: "Clean Expired Subscriber",
    description: "clean expired subscriber",
    period: ["0", "0", "0", "*", "*", "*"],
    immediate: true,
    require_path: "./bin/CleanExpiredSubscriber",
  },
  {
    name: "Weekly Member Audit",
    description: "queue member data for cleanup audit",
    period: ["0", "0", "3", "*", "*", "3"],
    immediate: false,
    require_path: "./bin/WeeklyMemberAudit",
  },
  {
    name: "Consume CleanUp Members",
    description: "process member cleanup queue",
    period: ["0", "*/15", "*", "*", "*", "3"],
    immediate: false,
    require_path: "./bin/ConsumeCleanUpMembers",
  },
  {
    name: "Monthly Reset",
    description: "reset monthly message records",
    period: ["0", "0", "0", "1", "*", "*"],
    immediate: false,
    require_path: "./bin/MonthlyReset",
  },
  {
    name: "Advancement Delivery",
    description: "deliver achievement titles",
    period: ["0", "0", "3", "*", "*", "*"],
    immediate: false,
    require_path: "./bin/AdvancementDelivery",
  },
  {
    name: "Daily Quest Process",
    description: "process daily quest rewards",
    period: ["0", "*", "*", "*", "*", "*"],
    immediate: true,
    require_path: "./bin/DailyQuestProcess",
  },
];
