// eslint-disable-next-line no-unused-vars
const { Knex } = require("knex");

const CATEGORIES = [
  { key: "chat", name: "聊天", icon: "💬", order: 1 },
  { key: "gacha", name: "轉蛋", icon: "🎰", order: 2 },
  { key: "janken", name: "猜拳", icon: "✊", order: 3 },
  { key: "world_boss", name: "世界王", icon: "👾", order: 4 },
  { key: "social", name: "社交", icon: "🌟", order: 5 },
];

const ACHIEVEMENTS = [
  {
    category: "chat",
    key: "chat_100",
    name: "話匣子",
    description: "累計發言 100 則",
    icon: "💬",
    type: "milestone",
    rarity: 0,
    target_value: 100,
    reward_stones: 50,
    order: 1,
  },
  {
    category: "chat",
    key: "chat_1000",
    name: "話題製造機",
    description: "累計發言 1,000 則",
    icon: "💬",
    type: "milestone",
    rarity: 1,
    target_value: 1000,
    reward_stones: 200,
    order: 2,
  },
  {
    category: "chat",
    key: "chat_5000",
    name: "鍵盤戰神",
    description: "累計發言 5,000 則",
    icon: "⌨️",
    type: "milestone",
    rarity: 2,
    target_value: 5000,
    reward_stones: 500,
    order: 3,
  },
  {
    category: "chat",
    key: "chat_night_owl",
    name: "夜貓子",
    description: "在凌晨 3-4 點發訊息",
    icon: "🦉",
    type: "hidden",
    rarity: 1,
    target_value: 1,
    reward_stones: 150,
    order: 4,
  },
  {
    category: "chat",
    key: "chat_multi_group",
    name: "社交蝴蝶",
    description: "在 5 個不同群組發言",
    icon: "🦋",
    type: "social",
    rarity: 1,
    target_value: 5,
    reward_stones: 200,
    order: 5,
  },
  {
    category: "gacha",
    key: "gacha_first",
    name: "初次轉蛋",
    description: "第一次抽轉蛋",
    icon: "🎰",
    type: "milestone",
    rarity: 0,
    target_value: 1,
    reward_stones: 30,
    order: 1,
  },
  {
    category: "gacha",
    key: "gacha_100",
    name: "轉蛋達人",
    description: "累計抽 100 次",
    icon: "🎰",
    type: "milestone",
    rarity: 1,
    target_value: 100,
    reward_stones: 200,
    order: 2,
  },
  {
    category: "gacha",
    key: "gacha_500",
    name: "課金戰士",
    description: "累計抽 500 次",
    icon: "💎",
    type: "milestone",
    rarity: 2,
    target_value: 500,
    reward_stones: 500,
    order: 3,
  },
  {
    category: "gacha",
    key: "gacha_collector_50",
    name: "蒐藏新手",
    description: "收集 50 種不同角色",
    icon: "📦",
    type: "milestone",
    rarity: 1,
    target_value: 50,
    reward_stones: 200,
    order: 4,
  },
  {
    category: "gacha",
    key: "gacha_lucky",
    name: "歐洲人",
    description: "單次十連抽出 3 張以上 3★",
    icon: "🍀",
    type: "hidden",
    rarity: 3,
    target_value: 1,
    reward_stones: 300,
    order: 5,
  },
  {
    category: "janken",
    key: "janken_first_win",
    name: "出拳入門",
    description: "猜拳首勝",
    icon: "✊",
    type: "milestone",
    rarity: 0,
    target_value: 1,
    reward_stones: 30,
    order: 1,
  },
  {
    category: "janken",
    key: "janken_win_50",
    name: "猜拳好手",
    description: "累計贏 50 場",
    icon: "✊",
    type: "milestone",
    rarity: 1,
    target_value: 50,
    reward_stones: 200,
    order: 2,
  },
  {
    category: "janken",
    key: "janken_streak_5",
    name: "連勝新星",
    description: "連勝 5 場",
    icon: "🔥",
    type: "challenge",
    rarity: 1,
    target_value: 5,
    reward_stones: 200,
    order: 3,
  },
  {
    category: "janken",
    key: "janken_streak_10",
    name: "不敗拳王",
    description: "連勝 10 場",
    icon: "👑",
    type: "challenge",
    rarity: 2,
    target_value: 10,
    reward_stones: 500,
    order: 4,
  },
  {
    category: "janken",
    key: "janken_challenged_10",
    name: "眾矢之的",
    description: "被 10 個不同用戶挑戰",
    icon: "🎯",
    type: "social",
    rarity: 1,
    target_value: 10,
    reward_stones: 200,
    order: 5,
  },
  {
    category: "world_boss",
    key: "boss_first_kill",
    name: "初陣",
    description: "第一次參與世界王",
    icon: "⚔️",
    type: "milestone",
    rarity: 0,
    target_value: 1,
    reward_stones: 50,
    order: 1,
  },
  {
    category: "world_boss",
    key: "boss_level_10",
    name: "見習勇者",
    description: "世界王等級達 10",
    icon: "🛡️",
    type: "milestone",
    rarity: 1,
    target_value: 10,
    reward_stones: 200,
    order: 2,
  },
  {
    category: "world_boss",
    key: "boss_level_50",
    name: "精英冒險者",
    description: "世界王等級達 50",
    icon: "⚔️",
    type: "milestone",
    rarity: 2,
    target_value: 50,
    reward_stones: 500,
    order: 3,
  },
  {
    category: "world_boss",
    key: "boss_top_damage",
    name: "一刀入魂",
    description: "任一場世界王戰鬥中傷害排名第一",
    icon: "💥",
    type: "hidden",
    rarity: 3,
    target_value: 1,
    reward_stones: 300,
    order: 4,
  },
  {
    category: "social",
    key: "social_first_command",
    name: "指令新手",
    description: "第一次使用任何指令",
    icon: "📋",
    type: "milestone",
    rarity: 0,
    target_value: 1,
    reward_stones: 30,
    order: 1,
  },
  {
    category: "social",
    key: "social_all_features",
    name: "全能玩家",
    description: "使用過聊天/轉蛋/猜拳/世界王各一次",
    icon: "🏆",
    type: "challenge",
    rarity: 2,
    target_value: 4,
    reward_stones: 300,
    order: 2,
  },
  {
    category: "social",
    key: "social_veteran_30d",
    name: "老玩家",
    description: "註冊超過 30 天",
    icon: "📅",
    type: "milestone",
    rarity: 1,
    target_value: 1,
    reward_stones: 150,
    order: 3,
  },
  {
    category: "social",
    key: "social_invite_group",
    name: "推廣大使",
    description: "Bot 被邀請進群時你是群組成員",
    icon: "📢",
    type: "hidden",
    rarity: 1,
    target_value: 1,
    reward_stones: 200,
    order: 4,
  },
  {
    category: "social",
    key: "social_easter_egg",
    name: "彩蛋獵人",
    description: "觸發隱藏彩蛋指令",
    icon: "🥚",
    type: "hidden",
    rarity: 3,
    target_value: 1,
    reward_stones: 300,
    order: 5,
  },
];

const TITLES = [
  {
    key: "chat_king_1",
    name: "話語霸權",
    description: "聊天排名第一",
    icon: "👑",
    rarity: 2,
    order: 1,
  },
  {
    key: "chat_king_2",
    name: "話術小丑",
    description: "聊天排名第二",
    icon: "🤡",
    rarity: 1,
    order: 2,
  },
  {
    key: "chat_king_3",
    name: "話語大師",
    description: "聊天排名第三",
    icon: "🎓",
    rarity: 1,
    order: 3,
  },
  {
    key: "gacha_king_1",
    name: "轉蛋蒐藏家",
    description: "轉蛋收集排名第一",
    icon: "🎰",
    rarity: 2,
    order: 4,
  },
  {
    key: "gacha_king_2",
    name: "轉蛋藝術家",
    description: "轉蛋收集排名第二",
    icon: "🎨",
    rarity: 1,
    order: 5,
  },
  {
    key: "gacha_king_3",
    name: "轉蛋家",
    description: "轉蛋收集排名第三",
    icon: "🎲",
    rarity: 1,
    order: 6,
  },
  {
    key: "gacha_rich_1",
    name: "女神富豪",
    description: "女神石持有排名第一",
    icon: "💰",
    rarity: 2,
    order: 7,
  },
  {
    key: "gacha_rich_2",
    name: "女神貴族",
    description: "女神石持有排名第二",
    icon: "💎",
    rarity: 1,
    order: 8,
  },
  {
    key: "gacha_rich_3",
    name: "女神騎士",
    description: "女神石持有排名第三",
    icon: "🛡️",
    rarity: 1,
    order: 9,
  },
  {
    key: "janken_king",
    name: "拳王",
    description: "猜拳最高評分",
    icon: "👊",
    rarity: 2,
    order: 10,
  },
  {
    key: "janken_ruki",
    name: "猜拳小菜鳥",
    description: "猜拳新手",
    icon: "🐣",
    rarity: 0,
    order: 11,
  },
  {
    key: "janken_loser",
    name: "輸到脫褲",
    description: "猜拳最多敗場",
    icon: "😭",
    rarity: 0,
    order: 12,
  },
  {
    key: "janken_drawer",
    name: "平局高手",
    description: "猜拳最多平手",
    icon: "🤝",
    rarity: 0,
    order: 13,
  },
  {
    key: "progressors",
    name: "攻略組",
    description: "世界王等級前 1%",
    icon: "⚔️",
    rarity: 2,
    order: 14,
  },
  {
    key: "leechers",
    name: "躺分組",
    description: "世界王等級後 1%",
    icon: "😴",
    rarity: 0,
    order: 15,
  },
  {
    key: "system_manager",
    name: "至高神",
    description: "系統管理員",
    icon: "🌌",
    rarity: 3,
    order: 0,
  },
];

/**
 * @param {Knex} knex
 */
exports.up = async function (knex) {
  await knex("achievement_categories").insert(CATEGORIES);

  const categories = await knex("achievement_categories").select("id", "key");
  const categoryMap = {};
  categories.forEach(c => {
    categoryMap[c.key] = c.id;
  });

  const achievements = ACHIEVEMENTS.map(({ category, ...rest }) => ({
    ...rest,
    category_id: categoryMap[category],
  }));
  await knex("achievements").insert(achievements);

  await knex("titles").insert(TITLES);
};

/**
 * @param {Knex} knex
 */
exports.down = async function (knex) {
  await knex("user_titles").delete();
  await knex("titles").delete();
  await knex("user_achievement_progress").delete();
  await knex("user_achievements").delete();
  await knex("achievements").delete();
  await knex("achievement_categories").delete();
};
