openapi: 3.0.3
info:
  title: LINE Webhook API
  description: |
    LINE Bot Webhook 端點，用於接收 LINE 平台發送的事件。
    此 API 遵循 LINE Messaging API Webhook 規範。
  version: 1.0.0
  contact:
    name: Redive LineBot Team

servers:
  - url: http://localhost:3000
    description: 開發環境
  - url: https://api.example.com
    description: 生產環境

paths:
  /line/webhook:
    post:
      summary: 接收 LINE Webhook 事件
      description: |
        接收並處理來自 LINE 平台的 Webhook 事件。

        ## 安全性
        - 所有請求必須包含有效的 `X-Line-Signature` header
        - 簽名使用 HMAC-SHA256 演算法驗證

        ## 處理流程
        1. 驗證請求簽名
        2. 冪等性檢查（過濾重複事件）
        3. 透過 Middleware 鏈處理每個事件
        4. 返回 200 OK（無論處理結果）
      operationId: handleWebhook
      tags:
        - LINE Webhook
      security:
        - lineSignature: []
      parameters:
        - name: X-Line-Signature
          in: header
          required: true
          description: |
            LINE 平台生成的簽名，用於驗證請求真實性。
            使用 Channel Secret 和請求 body 計算的 HMAC-SHA256 摘要（Base64 編碼）。
          schema:
            type: string
            example: "wqJD7WAIZhWcXThMCf8jZnwG3Hmn7EF36plkQGkj48w="
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WebhookRequestBody"
            examples:
              messageEvent:
                summary: 文字訊息事件
                value:
                  destination: "Uxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                  events:
                    - type: "message"
                      webhookEventId: "01H810YECXQQZ37VAXPF6H9E6T"
                      timestamp: 1692251666727
                      mode: "active"
                      replyToken: "38ef843bde154d9b91c21320ffd17a0f"
                      source:
                        type: "user"
                        userId: "U4af4980629..."
                      deliveryContext:
                        isRedelivery: false
                      message:
                        type: "text"
                        id: "468789577898262530"
                        text: "Hello!"
                        quoteToken: "q3Plxr4AgKd..."
              followEvent:
                summary: 加入好友事件
                value:
                  destination: "Uxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                  events:
                    - type: "follow"
                      webhookEventId: "01H810YECXQQZ37VAXPF6H9E6U"
                      timestamp: 1692251666800
                      mode: "active"
                      replyToken: "48ef843bde154d9b91c21320ffd17a1f"
                      source:
                        type: "user"
                        userId: "U4af4980629..."
                      deliveryContext:
                        isRedelivery: false
              postbackEvent:
                summary: Postback 事件
                value:
                  destination: "Uxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                  events:
                    - type: "postback"
                      webhookEventId: "01H810YECXQQZ37VAXPF6H9E6V"
                      timestamp: 1692251666900
                      mode: "active"
                      replyToken: "58ef843bde154d9b91c21320ffd17a2f"
                      source:
                        type: "user"
                        userId: "U4af4980629..."
                      deliveryContext:
                        isRedelivery: false
                      postback:
                        data: "action=buy&itemid=123"
      responses:
        "200":
          description: |
            事件已接收。

            **注意**: 即使事件處理失敗，也會返回 200 OK。
            這是 LINE 平台的要求，以避免不必要的重試。
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
        "400":
          description: 請求格式錯誤（JSON 解析失敗）
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                statusCode: 400
                message: "Invalid JSON format"
                error: "Bad Request"
        "401":
          description: 簽名驗證失敗
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                statusCode: 401
                message: "Signature validation failed"
                error: "Unauthorized"

components:
  securitySchemes:
    lineSignature:
      type: apiKey
      in: header
      name: X-Line-Signature
      description: LINE 平台生成的 HMAC-SHA256 簽名

  schemas:
    WebhookRequestBody:
      type: object
      required:
        - destination
        - events
      properties:
        destination:
          type: string
          description: Bot 的 User ID
          example: "Uxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        events:
          type: array
          description: 事件陣列
          items:
            $ref: "#/components/schemas/WebhookEvent"

    WebhookEvent:
      type: object
      required:
        - type
        - webhookEventId
        - timestamp
        - mode
        - source
        - deliveryContext
      properties:
        type:
          type: string
          description: 事件類型
          enum:
            - message
            - follow
            - unfollow
            - join
            - leave
            - memberJoin
            - memberLeave
            - postback
            - beacon
            - accountLink
        webhookEventId:
          type: string
          description: 事件唯一識別碼
          example: "01H810YECXQQZ37VAXPF6H9E6T"
        timestamp:
          type: integer
          format: int64
          description: 事件發生時間（Unix 毫秒）
          example: 1692251666727
        mode:
          type: string
          description: Bot 模式
          enum:
            - active
            - standby
        source:
          $ref: "#/components/schemas/EventSource"
        deliveryContext:
          $ref: "#/components/schemas/DeliveryContext"
        replyToken:
          type: string
          description: 回覆用 Token（部分事件有）
          example: "38ef843bde154d9b91c21320ffd17a0f"
        message:
          $ref: "#/components/schemas/MessageObject"
        postback:
          $ref: "#/components/schemas/PostbackObject"

    EventSource:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          description: 來源類型
          enum:
            - user
            - group
            - room
        userId:
          type: string
          description: 使用者 ID
          example: "U4af4980629..."
        groupId:
          type: string
          description: 群組 ID（僅 group 類型）
          example: "Ca56f94637c..."
        roomId:
          type: string
          description: 聊天室 ID（僅 room 類型）

    DeliveryContext:
      type: object
      required:
        - isRedelivery
      properties:
        isRedelivery:
          type: boolean
          description: 是否為重新發送的事件
          example: false

    MessageObject:
      type: object
      required:
        - type
        - id
      properties:
        type:
          type: string
          description: 訊息類型
          enum:
            - text
            - image
            - video
            - audio
            - file
            - location
            - sticker
        id:
          type: string
          description: 訊息 ID
          example: "468789577898262530"
        text:
          type: string
          description: 文字內容（僅 text 類型）
        quoteToken:
          type: string
          description: 引用 Token

    PostbackObject:
      type: object
      required:
        - data
      properties:
        data:
          type: string
          description: Postback 資料
          example: "action=buy&itemid=123"
        params:
          type: object
          description: 額外參數（日期選擇器等）

    ErrorResponse:
      type: object
      required:
        - statusCode
        - message
        - error
      properties:
        statusCode:
          type: integer
          description: HTTP 狀態碼
          example: 401
        message:
          type: string
          description: 錯誤訊息
          example: "Signature validation failed"
        error:
          type: string
          description: 錯誤類型
          example: "Unauthorized"

tags:
  - name: LINE Webhook
    description: LINE Bot Webhook 端點
