openapi: 3.0.3
info:
  title: Redive LineBot API - Health Check
  description: 健康檢查端點，用於驗證服務狀態
  version: 0.1.0

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /health:
    get:
      summary: 健康檢查
      description: 檢查服務是否正常運行，包含資料庫與快取連線狀態
      operationId: getHealth
      tags:
        - Health
      responses:
        "200":
          description: 服務正常
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
              example:
                status: ok
                timestamp: "2024-12-07T12:00:00.000Z"
                services:
                  database: healthy
                  redis: healthy
        "503":
          description: 服務異常
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
              example:
                status: error
                timestamp: "2024-12-07T12:00:00.000Z"
                services:
                  database: unhealthy
                  redis: healthy

  /health/live:
    get:
      summary: 存活檢查
      description: 簡易檢查服務是否存活（Kubernetes liveness probe）
      operationId: getLiveness
      tags:
        - Health
      responses:
        "200":
          description: 服務存活
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

  /health/ready:
    get:
      summary: 就緒檢查
      description: 檢查服務是否準備好接受請求（Kubernetes readiness probe）
      operationId: getReadiness
      tags:
        - Health
      responses:
        "200":
          description: 服務就緒
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        "503":
          description: 服務尚未就緒

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum: [ok, error]
          description: 整體服務狀態
        timestamp:
          type: string
          format: date-time
          description: 檢查時間
        services:
          type: object
          properties:
            database:
              type: string
              enum: [healthy, unhealthy]
              description: 資料庫連線狀態
            redis:
              type: string
              enum: [healthy, unhealthy]
              description: Redis 連線狀態
